#!/bin/sh

read -p "Are you certain you want to push to production? (Y/N)" confirm
deploykey=$(<.deploykey_production)
case $confirm in
	[Yy]* ) ./deploy $deploykey; break;;
	* ) echo "Cancelled";;
esac
