#!/bin/sh

read -p "Are you certain you want to push to production? (Y/N)" confirm
deploykey=$(cat .deploykey_production)
case $confirm in
	[Yy]* ) echo "Deploying to" $deploykey; ./deploy $deploykey; break;;
	* ) echo "Cancelled";;
esac
